### ISSUE TITLE
I found a mistake.

### ISSUE THREAD

**Issue by 849025143** [spigot-gillesm/RPGChest-Premium#19]
/rpgc m
`[20:41:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rpgc m' in me.gilles_m.RPGChestPremium.goto. .aUx(rpgchest)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:162) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.SKELETON_SPAWN_EGG
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.Material.valueOf(Material.java:71) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at me.gilles_m.RPGChestPremium.goto. .coM1.int(SourceFile:38) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .coM1.do(SourceFile:178) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .coM1.for(SourceFile:262) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .Com2.do(SourceFile:129) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .Com2.if(SourceFile:58) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .Com2.do(SourceFile:34) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .cOm2.do(SourceFile:17) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .aUx.do(SourceFile:395) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .Aux.execute(SourceFile:32) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        ... 14 more`

**Comment by spigot-gillesm** [comment]
Are you sure you're using the latest RPGChest file? The 2.2.3.0 version named RPGChest-2.3.0.0.jar? I'm looking into the file and the error is displaying something that does not exist

**Comment by 849025143** [comment]
I saw plugin.yml，version: 2.3.0.0

**Comment by spigot-gillesm** [comment]
I'm sorry to insist but can you check in your /plugins server folder if RPGChest-2.3.0.0 is the only copy of RPGChest present? (And that the previous legacy version has been deleted from the folder)

**Comment by 849025143** [comment]
I used Yum to load it, so it can't be used normally. I restart the server and then return to normal.
Thank you for your help and wish your plug-ins more and more popular.

**Comment by 849025143** [comment]
I have another mistake.. After I restart the server.
 `[21:10:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rpgc m' in me.gilles_m.RPGChestPremium.goto. .aUX(rpgchest)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:162) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
        at me.gilles_m.RPGChestPremium.goto. .cOm2.do(SourceFile:39) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .Com6.if(SourceFile:221) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .Com6.do(SourceFile:35) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .COm6.do(SourceFile:17) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .aUX.do(SourceFile:253) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .auX.execute(SourceFile:34) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        ... 14 more`

**Comment by spigot-gillesm** [comment]
It seems that there's a problem retrieving a particular item from the items.yml file. Could you check if you haven't put anything "weird" in this file?

**Comment by 849025143** [comment]
I haven't changed him, I tried to delete it.

I managed to solve the problem.

I find some languages can't be changed. Can you change it?

**Comment by spigot-gillesm** [comment]
Can you tell me what the problem was?

Please name me the languages you'd like to be able to configure?

**Comment by 849025143** [comment]
Chinese

**Comment by spigot-gillesm** [comment]
Oh I meant the messages that are not in the language file sorry

**Comment by 849025143** [comment]
Maximum amount；Minimum amount；Set external item；material/Item name................

**Comment by spigot-gillesm** [comment]
Oh well you mean the GUI entries. I've started to translate some of them but not all as it takes quite a long time to do (not difficult tho, just long). The rest is coming ;) I'm closing the issue but feel free to re-open it (or open another one) if you need to

**Comment by 849025143** [comment]
okay
