### ISSUE TITLE
Bug with installation of the plugin 

### ISSUE THREAD

**Issue by Ambroseeee** [spigot-gillesm/RPGChest-Premium#2]
Hi ! 

I just buy your plugin and got a problem when i install it . My server doesnt load it 

My server is an 1.14.4 server and i got other plugins ( i give you a picture of my plugins ) 
![Capture d’écran (18)](https://user-images.githubusercontent.com/40477842/69654706-2109ee00-106d-11ea-8544-d5d248612619.png)

I found this error in the console too :
 Could not load 'plugins/RPGChest-1.8.2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:168) ~[minecraft_server.jar:git-Spigot-56f8471-56118c6]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:138) [minecraft_server.jar:git-Spigot-56f8471-56118c6]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [minecraft_server.jar:git-Spigot-56f8471-56118c6]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202) [minecraft_server.jar:git-Spigot-56f8471-56118c6]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [minecraft_server.jar:git-Spigot-56f8471-56118c6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_232]
at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_232]
at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_232]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_232]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_232]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:156) ~[minecraft_server.jar:git-Spigot-56f8471-56118c6]
... 5 more

I DOESNT install the legacy one but the other 

Maybe i doing something wrong ? If you need any other information please tell me 

Thx for reading this

**Comment by spigot-gillesm** [comment]
Hello,

I'm sorry for the inconvenience and I'm looking into it right now. As soon as I come to a fix I'll message you back
I just tried it on my own test server 'paper version 1.14.4) and it could load properly so I suppose there's something wrong in your server's end. Can you send me additional information? Also, it might be easier for us to fix it using Discord as it might get messy here: Gilles_m#8127

I hope we'll be able to fix it quickly
