### ISSUE TITLE
A Error

### ISSUE THREAD

**Issue by 849025143** [spigot-gillesm/RPGChest-Premium#21]
`[11:18:55 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rpgc m' in me.gilles_m.RPGChestPremium.goto. .aUX(rpgchest)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:162) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.iron_nugget
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.Material.valueOf(Material.java:71) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at me.gilles_m.RPGChestPremium.goto. .NUL.do(SourceFile:44) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .COm6.do(SourceFile:19) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .aUX.do(SourceFile:253) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .auX.execute(SourceFile:34) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        ... 14 more`

**Comment by spigot-gillesm** [comment]
Did you download the latest RPGChest version? (2.3.0.1)

**Comment by 849025143** [comment]
yes, 2.3.0.1

**Comment by spigot-gillesm** [comment]
Alright I’ll see what I have to do and push a fix if needed

**Comment by 849025143** [comment]
okay

**Comment by spigot-gillesm** [comment]
Okay I've found the problem. I've already fixed it and I thought I added the fix in the previous update but it appears I forgot. I'm pushing the update right now

**Comment by spigot-gillesm** [comment]
I updated and tested the new build. The problem should be fixed now! Feel free to open a new ticket if you notice any other bug
