### ISSUE TITLE
I'm in trouble

### ISSUE THREAD

**Issue by 849025143** [spigot-gillesm/RPGChest-Premium#22]
Occurs when a project is created.
`[14:17:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rpgc m' in me.gilles_m.RPGChestPremium.goto. .aUX(rpgchest)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:162) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
        at me.gilles_m.RPGChestPremium.goto. .coM2.do(SourceFile:39) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .COm6.if(SourceFile:221) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .COm6.do(SourceFile:35) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .CoM6.do(SourceFile:17) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .aUX.do(SourceFile:253) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .auX.execute(SourceFile:34) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        ... 14 more`

**Comment by 849025143** [comment]
Can it support custom items?

**Comment by spigot-gillesm** [comment]
Hello!

There's an error in your items.yml file: an item material is invalid. Please check your file for any mistake in your items 'Material' option. If you need a list of all Minecraft Material name, I can give you a link
You can create custom items using RPGChest or use items coming from other plugins (such as MMOItems or MythicMobs). To learn how to do that please read RPGChest wiki : https://github.com/spigot-gillesm/RPGChest-Premium/wiki/Setting-custom-items and: https://github.com/spigot-gillesm/RPGChest-Premium/wiki/Setting-external-items
Here is the list of all the plugin compatibilities: https://github.com/spigot-gillesm/RPGChest-Premium/wiki/Compatibilities

**Comment by spigot-gillesm** [comment]
I'm closing the ticket, Feel free to reopen it if your problem persists
