### ISSUE TITLE
error When I create container

### ISSUE THREAD

**Issue by justicebearx** [spigot-gillesm/RPGChest-Premium#28]
[23:30:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RPGChest v3.2.4
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-9489fbb]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-9489fbb]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-9489fbb]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-9489fbb]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274) [CraftEventFactory.class:git-CatServer-1.12.2-9489fbb]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:241) [CraftEventFactory.class:git-CatServer-1.12.2-9489fbb]
        at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1064) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at com.gilles_m.RPGChestPremium2.gui.container_gui.ContainerMenu$3.writeValue(ContainerMenu.java:103) ~[?:?]
        at com.gilles_m.RPGChestPremium.lib.menu.listener.ChatListener.onPlayerClickBlockEvent(ChatListener.java:87) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-9489fbb]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:118) ~[PluginClassLoader.class:git-CatServer-1.12.2-9489fbb]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-9489fbb]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at com.gilles_m.RPGChestPremium2.gui.container_gui.ContainerMenu$3.writeValue(ContainerMenu.java:103) ~[?:?]
        at com.gilles_m.RPGChestPremium.lib.menu.listener.ChatListener.onPlayerClickBlockEvent(ChatListener.java:87) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-9489fbb]
        ... 18 more

**Comment by spigot-gillesm** [comment]
Hello, what version of Minecraft are you using? The error is supposed to
happen only in older versions of the game (prior to Minecraft 1.13). Right
now the plugin is not compatible with versions prior to 1.13 and not tested
with versions prior to 1.16

Le ven. 13 nov. 2020 à 16:31, justicebearx <notifications@github.com> a
écrit :

**Comment by justicebearx** [comment]
use version 1.12.2 of Minecraft
Please tell me which version I should use

**Comment by spigot-gillesm** [comment]
You should use version 1.16.4 as it's the latest and most stable version.
If it's not possible then you'll have to wait 'till I make it compatible
with version 1.12 (in a few days at max)

Le ven. 13 nov. 2020 à 17:30, justicebearx <notifications@github.com> a
écrit :

**Comment by justicebearx** [comment]
OK
